s1=set()
print(s1)
print()
print(type(s1))
print()
print("adding emp info..")
s1.add(100)
s1.add("siva")
s1.add(10000)
s1.add("iot dovp")
s1.add('tcs')
print(s1)
print()
print("removing empoly info")