x,y,z=32,5,2022
print("..Date..")
print(x,y,z,sep="/")
print()
print("...another date..")
print(x,y,z,sep="-")
print()
print("..amount..")
print(x,y,z,sep=",")
print()
print("..time..")
print(x,y,z,sep=":")
print()
print("...digital time...")
print(x,y,z,sep='::')
print()